koko_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500
  # Position Controllers ---------------------------------------
  joint_positions_controller:
    # TODO: resolve redundant constraint
    paired_constraints: [1, 2, 3, 4]
    endlink: 'forearm_link'
    filter_length: 20
    type: koko_controllers/InverseDynamicsController
    root_name: koko
    zero_g_mode: false
    base_roll_joint:
      p: 0.0
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 3.3
      min_angle: -2.2
    shoulder_lift_joint:
      #p: 100
      p: 0.0
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 0.5
      min_angle: -2.2
    shoulder_roll_joint:
      #p: 100
      p: 0.0
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 2.6
      min_angle: -2.6
    elbow_lift_joint:
      # p: 80
      p: 0.0
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 0.5
      min_angle: -2.2
    elbow_roll_joint:
      #p: 50
      p: 0.0
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 2.6
      min_angle: -2.6
