koko_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500
  # Position Controllers ---------------------------------------
  joint_positions_controller:
    # TODO: resolve redundant constraint
    paired_constraints: [1, 2, 3, 4]
    endlink: 'upper_arm_lift_link'
    filter_length: 20
    type: koko_controllers/InverseDynamicsController
    root_name: koko
    zero_g_mode: false
    base_roll_joint:
      p: 0.0
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 3.3
      min_angle: -2.2
    shoulder_lift_joint:
      #p: 100
      p: 0.0
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 0.5
      min_angle: -2.2
    shoulder_roll_joint:
      #p: 100
      p: 0.0
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 2.6
      min_angle: -2.6
    elbow_lift_joint:
      # p: 80
      p: 0.0
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 0.5
      min_angle: -2.2
    elbow_roll_joint:
      #p: 50
      p: 0.0
      d: 0.0
      id: 1.0
      max_torque: 30
      min_torque: -30
      max_angle: 2.6
      min_angle: -2.6

  cartesian_pose_controller:
    endlink: 'wrist_roll_link'
    paired_constraints: [1, 2, 3, 4, 5, 6]
    filter_length: 20
    type: koko_controllers/CartesianPoseController
    p_gains: [100, 100, 100, 1, 1, 1]
    d_gains: [5.0, 5.0, 5.0, 0.2, 0.2, 0.2]
    posture_control: false
    posture_gain: 10.0
    posture_target: [0.0, 0.54, 1.19, -1.19, -1.33, 0.78, -2.29]
    z_offset_controller: 0.0
    root_name: koko
    base_roll_joint:
      id: 0.0
      max_torque: 30
      min_torque: -30
      max_angle: 3.3
      min_angle: -2.2
    shoulder_lift_joint:
      id: 0.55
      max_torque: 30
      min_torque: -30
      max_angle: 0.5
      min_angle: -2.2
    shoulder_roll_joint:
      id: 0.5
      max_torque: 30
      min_torque: -30
      max_angle: 2.6
      min_angle: -2.6
    elbow_lift_joint:
      id: 0.7
      max_torque: 30
      min_torque: -30
      max_angle: 0.5
      min_angle: -2.2
    elbow_roll_joint:
      id: 0.0
      max_torque: 30
      min_torque: -30
      max_angle: 2.6
      min_angle: -2.6
    wrist_lift_joint:
      id: 0
      max_torque: 30
      min_torque: -30
      max_angle: 0.5
      min_angle: -2.2
    wrist_roll_joint:
      id: 0.0
      max_torque: 30
      min_torque: -30
      max_angle: 2.6
      min_angle: -2.6
